### ISSUE TITLE
NoMethodError, when creating a new User

### ISSUE THREAD

**Issue by r3id** [Sorcery/sorcery#270]
### Configuration

- Sorcery Version: `0.15.0`
- Ruby Version: `3.0.0`
- Framework: `Rails 6.1.1`
- Platform: `macOS 11.1`

### Expected Behavior
A new user is meant to be created.

### Actual Behavior
Since updating to **sorcery 0.15.0** I am getting the following error when I try to run User.create in the rails console.

```
NoMethodError (undefined method `after_save' for {:if=>#<Proc:0x00007fcb22b96cd0 /Users/alan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorcery-0.15.0/lib/sorcery/model.rb:69>}:Hash)
```

### Steps to Reproduce
See below for when I run the `User.create`

```
irb(main):001:0> user = User.create(email: 'alan@example.com')
  TRANSACTION (0.1ms)  BEGIN
  User Exists? (1.1ms)  SELECT 1 AS one FROM "users" WHERE "users"."slug" = $1 LIMIT $2  [["slug", "8c8b4b303a"], ["LIMIT", 1]]
  User Create (0.9ms)  INSERT INTO "users" ("slug", "email", "created_at", "updated_at") VALUES ($1, $2, $3, $4) 
  RETURNING "id"  [["slug", "8c8b4b303a"], ["email", "alan@example.com"], 
                                  ["created_at", "2021-01-18 12:05:58.962942"], 
                                  ["updated_at", "2021-01-18 12:05:58.962942"]]
  TRANSACTION (0.2ms)  ROLLBACK
Traceback (most recent call last):
        1: from (irb):1:in `<main>'
NoMethodError (undefined method `after_save' for {:if=>#<Proc:0x00007fcb22b96cd0
/Users/alan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorcery-0.15.0/lib/sorcery/model.rb:69>}:Hash)

```

**Comment by r3id** [comment]
I am thinking this has something to do with Ruby 3.0.0, as it was working fine with Ruby 2.7.2

**Comment by wout** [comment]
@r3id I'm using the exact same configuration for two apps (Ruby 3.0.0, Rails 6.1.1, Sorcery 0.15.0) everything works fine.

Am I right you don't have a password on your model? And if so, could that have something to do with it? Because the errors seems to come from here:

```rb
# sorcery/model.rb:69

sorcery_adapter.define_callback :after, :save, :clear_virtual_password, if: proc { |record|
  record.send(sorcery_config.password_attribute_name).present?
}
```

**Comment by r3id** [comment]
I have reverted back to Ruby 2.7.2 and all is working fine again.

@wout yeah mate, I am doing passwordless auth, and it works fine now I am back on Ruby 2.7.2. It's only when I upgraded to 3.0.0 that I am getting the error I posted about originally.

**Comment by r3id** [comment]
I was following [this tutorial](https://fullstackheroes.com/rails/sorcery-passwordless-authentication/) so maybe you can see what you get?

**Comment by wout** [comment]
@r3id Weird indeed. I'll have a look at the tut if I have a moment to spare.

**Comment by tomoyuki** [comment]
I am getting same error. 
* ruby 3.0.0
* Rails 6.1.1
* Sorcery 0.15.0

```
bin/rails g sorcery:install
bin/rails g sorcery:install user_activation --only-submodules
bin/rails db:migrate
bin/rails g mailer UserMailer
```
```ruby
# config/initializer/sorcery.rb

user.user_activation_mailer = UserMailer
```
```ruby
# app/models/user.rb

class User < ApplicationRecord
  authenticates_with_sorcery!
end
```

```ruby
# bin/rails c

[1] pry(main)> User.create!
NoMethodError: undefined method `before_create' for {:if=>#<Proc:0x0000000005d4a170 (Rails.root)/vendor/bundle/ruby/3.0.0/gems/sorcery-0.15.0/lib/sorcery/model/submodules/user_activation.rb:46>}:Hash
from (Rails.root)/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
```

No error occured before add submodule.
```ruby
# bin/rails c

[1] pry(main)> User.create!
  TRANSACTION (0.2ms)  BEGIN
  User Create (1.0ms)  INSERT INTO `users` (`created_at`, `updated_at`) VALUES ('2021-01-24 11:22:21.543210', '2021-01-24 11:22:21.543210')
  TRANSACTION (0.1ms)  ROLLBACK
ActiveRecord::NotNullViolation: Mysql2::Error: Field 'email' doesn't have a default value
```

**Comment by Olivier4murs** [comment]
I'm not sure about my change but maybe you have just to add "&" before options in active_record_adapter.rb :

```
def define_callback(time, event, method_name, options = {})
    @klass.send "#{time}_#{event}", method_name, &options.slice(:if, :on)
end
```

**Comment by athix** [comment]
> I just discovered the master branch is already fixed...

Working on cutting a new release in the near future...

**Comment by athix** [comment]
Version 0.16.0 has been released, can someone try it and see if this issue has been resolved?

**Comment by athix** [comment]
Going to assume this is fixed and close the issue out, if anyone still has problems please comment on this and I'll reopen it.

**Comment by ccokme** [comment]
@athix still facing this error, env:

ruby-3.0.1
sorcery-0.16.1
mongoid-7.3.0
rails-6.0.3.2

error:
`
NoMethodError:
       undefined method `after_save' for {:if=>#<Proc:0x00007fb882a81cf8 /usr/local/rvm/gems/ruby-3.0.1/gems/sorcery-0.16.1/lib/sorcery/model.rb:69>}:Hash
     # /usr/local/rvm/gems/ruby-3.0.1/gems/mongoid-7.3.0/lib/mongoid/interceptable.rb:135:in `run_callbacks'
`

**Comment by athix** [comment]
@ccokme Would you be willing to create a new rails app and recreate the issue with as little code as possible? It would be immensely helpful for me tracking down where this is coming from.

**Comment by ccokme** [comment]
> @ccokme Would you be willing to create a new rails app and recreate the issue with as little code as possible? It would be immensely helpful for me tracking down where this is coming from.

Sure thing, i just create a new rails app with the same version of mongoig/rails/ruby/sorcery, https://github.com/ccokme/sorcery_test_app, you just have to run mongodb on your dev, and then enter the rails console:

```
3.0.1 :005 > User.new.save
/usr/local/rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:427:in `block in make_lambda': undefined method `after_save' for {:if=>#<Proc:0x00007fd42837cb30 /usr/local/rvm/gems/ruby-3.0.1/gems/sorcery-0.16.1/lib/sorcery/model.rb:69>}:Hash (NoMethodError)
```

**Comment by athix** [comment]
@ccokme Thank you! I'll take a look at this when I have the time and see if I can't figure out what the deal is.

**Comment by ccokme** [comment]
@athix Maybe it's related with the changes of lambda/proc parameters of ruby 3, i have changed the 

sorcery-0.16.1/lib/sorcery/adapters/mongoid_adapter.rb:35

from:
`@klass.send callback_name(time, event, options), method_name, options.slice(:if)`
to:
`@klass.send callback_name(time, event, options), method_name, **options.slice(:if)`

then it works, hope it helps.
