### ISSUE TITLE
NoMethodError in UsersController#create

### ISSUE THREAD

**Issue by uberdave** [Sorcery/sorcery#118]
I am having a time getting sorcery to work in rails v 4.2.10. Everything worked perfectly in 3.2.8.
I have run all the migrations in the wiki, and it seems that one issue solved, leads to the next. Now I receive the following error:
NoMethodError in UsersController#create
undefined method `activation_token=' for #<User:0x000055cf698caa08>

 class UsersController < ApplicationController
       
        skip_before_action :require_login, only: [:index, :new, :create, :activate]
          

          def index
            @users = User.all

             respond_to do |format|
             format.html # index.html.erb
             format.json { render json: @users }
            end
          end

        
          def show
            @user = User.find(params[:id])

             respond_to do |format|
             format.html # show.html.erb
              format.json { render json: @user }
            end
          end

         
          def new
            @user = User.new

            respond_to do |format|
              format.html # new.html.erb
              format.json { render json: @user }
            end
          end

        
          def edit
           @user = User.find(params[:id])
          end

    def create
           @user = User.new(permit_user_params)

            respond_to do |format|
              if @user.save
                format.html { render action: "thanks", notice: 'User was 
        successfully created.' }
                format.json { render json: @user, status: :created, 
location: @user }
              else
                 format.html { render action: "new" }
                 format.json { render json: @user.errors, status: 
 :unprocessable_entity }
             end
            end
          end

        
          def update
           @user = User.find(params[:id])

            respond_to do |format|
              if @user.update_attributes(params[:user])
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { head :no_content }
              else
                format.html { render action: "edit" }
                format.json { render json: @user.errors, status: :unprocessable_entity }
              end
            end
            end

         
         def destroy
            @user = User.find(params[:id])
            @user.destroy

            respond_to do |format|
              format.html { redirect_to users_url }
              format.json { head :no_content }
            end
          end

          def activate
          if (@user = User.load_from_activation_token(params[:id]))
            @user.activate!
            redirect_to(login_path, :notice => 'User was successfully activated.')
         else
            not_authenticated
          end
        end
        def thanks 
         respond_to do |format|
              format.html # thanks.html.erb
              format.json { render json: @user }
        end
       end
          private
            def permit_user_params
              params.require(:user).permit(:email, :password, :password_confirmation)
            end
          end

**Comment by uberdave** [comment]
Can't seem to get any help. I spent countless hours on this. Guess I'll completely remove sorcery and start over

**Comment by eablamb** [comment]
You may not have the user activation migrations.  I'd check your `db/schema.rb` to make sure your `users` table has the `activation_token` field.  If not, you will need to install the user activation submodule, which will include the appropriate migrations.
